server{
    listen 443 ssl;
    ssl_certificate cert.pem;
    ssl_certificate_key key.pem;
    location / {
        proxy_pass http://127.0.0.1:3000;
    }
}

----------------------------------------------------------------------------------
server{
    listen 80;
    loaction/{
        proxy_pass http:127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}